### ISSUE TITLE
Error TS2345

### ISSUE THREAD

**Issue by fareedpatel** [fareedpatel/SteamApp#2]
TypeScript error: app/app.ts(69,5): Error TS2345: Argument of type '{ provider: AuthProviders; method: AuthMethods; remember: string; scope: string[]; }' is not assignable to parameter of type 'AuthConfiguration'.
  Object literal may only specify known properties, and 'remember' does not exist in type 'AuthConfiguration'.

**Comment by gujiman** [comment]
note for future problem solving:

1) Go back to the original resp. were you forked it, and see if anyone had the same issue!

https://github.com/tomasvio/i2a2ea/issues/1

**Comment by fareedpatel** [comment]
So the version that worked for me was: 2.0.0-beta.3-0930330
